# First phase for build
FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# EACCES: permission denied, mkdir '/app/node_modules.cache'
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .
RUN npm run build


#second phase for NGINX
FROM nginx
# I want to copy over something from that other phase into html file. 
COPY --from=build  /app/build /usr/share/nginx/html
