version: '3'
services:
#Below container is responsible for hosting service for development server.
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  #Below container is responsible for testing, and re-running the test in case any changes in App.test.js.
  tests: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","start"]